apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.gradle-plugin-testing'

dependencies {
    compileOnly gradleApi()

    implementation 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone'

    compileOnly 'org.immutables:value::annotations'
    annotationProcessor 'org.immutables:value'

    compileOnly 'com.palantir.gradle.auto-parallelizable:auto-parallelizable-annotations'
    annotationProcessor 'com.palantir.gradle.auto-parallelizable:auto-parallelizable'

    gradlePluginForTesting 'com.palantir.baseline:gradle-baseline-java'
}

tasks.named('test').configure {
    dependsOn ':gradle-guide-error-prone:publishToMavenLocal'

    systemProperty 'gradleGuideErrorProneVersion', version
}



gradlePlugin {
    // do not add new task to publish to plugins.gradle.org
    automatedPublishing = false
}

gradleTestUtils {
    configurationCacheEnabled = true
}
