buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.75.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'

rootProject.name = 'gradle-guide-root'

include 'gradle-guide'
include 'gradle-guide-error-prone'
include 'internal-checks'
