com.fasterxml.jackson.*:* = 2.19.1
com.google.auto.service:* = 1.1.1
com.google.errorprone:error_prone_* = 2.49.0
com.google.guava:guava = 33.6.0-jre
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.gradle.auto-parallelizable:* = 1.4.0
com.palantir.safe-logging:* = 3.14.0
com.palantir.suppressible-error-prone:* = 2.28.0
net.ltgt.gradle:gradle-errorprone-plugin = 5.1.0
org.junit.jupiter:* = 6.0.3
org.assertj:* = 3.27.7
one.util:streamex = 0.8.4
org.immutables:* = 2.12.1
org.jetbrains:annotations = 26.1.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.47.0
org.checkerframework:checker-qual = 4.1.0
org.junit.platform:* = 6.0.3
