com.fasterxml.jackson.*:* = 2.19.1
com.google.auto.service:* = 1.1.1
com.google.errorprone:error_prone_* = 2.36.0
com.google.guava:guava = 33.5.0-jre
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.gradle.auto-parallelizable:* = 1.4.0
com.palantir.safe-logging:* = 3.11.0
com.palantir.suppressible-error-prone:* = 2.26.0
net.ltgt.gradle:gradle-errorprone-plugin = 4.4.0
org.junit.jupiter:* = 6.0.2
org.assertj:* = 3.27.6
one.util:streamex = 0.8.4
org.immutables:* = 2.12.1
org.jetbrains:annotations = 26.0.2

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
org.checkerframework:checker-qual = 3.53.0
org.junit.platform:* = 6.0.2
